version: 2

updates:
  - package-ecosystem: gomod
    directory: /
    schedule:
      interval: daily
    groups:
      k8s:
        patterns:
          - "k8s.io/*"

  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
